"""Regenerate fixed wire fixtures with pymavlink==2.4.49 (not a build dependency)."""
from importlib.metadata import version
from pathlib import Path

from pymavlink.dialects.v10 import common as v1
from pymavlink.dialects.v20 import common as v2

assert version("pymavlink") == "2.4.49"

SAMPLES = [
    ("heartbeat", (2, 3, 128, 4, 4, 3)),
    ("attitude", (1000, 0.25, -0.5, 1.5, 0, 0, 0)),
    ("global_position_int", (1000, 0, 0, 0, 42500, 0, 0, 0, 0)),
    ("optical_flow", (1000, 7, 12, -13, 0.5, -0.25, 220, 0.75)),
    ("optical_flow_rad", (1000, 9, 10000, 0.125, -0.25, 0, 0, 0, -120, 219, 20000, 1.25)),
    ("distance_sensor", (1000, 20, 400, 73, 0, 3, 25, 0)),
    ("altitude", (1000, 101, 102, 1, 3.25, 0, 0)),
]

lines = ["// Generated by generate_mavlink_telemetry_golden.py; pymavlink 2.4.49, common dialect.",
         "// Fixed fixtures let CTest run without Python or pymavlink.",
         "#pragma once", "#include <array>", "#include <cstdint>", "#include <string_view>",
         "namespace mavlink_golden {",
         "struct Packet { std::uint32_t id; bool v2; bool zero; bool signed_frame; std::string_view hex; };",
         "inline constexpr std::array<Packet, 35> packets{{"]
for dialect, is_v2 in [(v1, False), (v2, True)]:
    for name, values in SAMPLES:
        for zero in [False, True]:
            sender = dialect.MAVLink(None, srcSystem=42, srcComponent=17)
            sender.seq = 23
            cls = getattr(dialect, "MAVLink_" + name + "_message")
            message = cls(*([0] * len(values) if zero else values))
            wire = message.pack(sender)
            # Verify generated wire with the independent library's receiver too.
            decoded = dialect.MAVLink(None).parse_buffer(wire)
            assert len(decoded) == 1 and decoded[0].get_msgId() == cls.id
            lines.append(f'    {{{cls.id}, {str(is_v2).lower()}, {str(zero).lower()}, false, "{wire.hex()}"}}, // {name}')
for name, values in SAMPLES:
    sender = v2.MAVLink(None, srcSystem=42, srcComponent=17)
    sender.seq = 23
    sender.signing.secret_key = bytes(range(32))  # Public deterministic TEST key only.
    sender.signing.link_id = 5
    sender.signing.timestamp = 1234567
    sender.signing.sign_outgoing = True
    cls = getattr(v2, "MAVLink_" + name + "_message")
    wire = cls(*values).pack(sender)
    lines.append(f'    {{{cls.id}, true, false, true, "{wire.hex()}"}}, // signed {name}')
lines += ["}};", "} // namespace mavlink_golden", ""]
Path(__file__).with_name("mavlink_telemetry_golden.hpp").write_text("\n".join(lines), encoding="utf-8")
