// Generated by generate_mavlink_telemetry_golden.py; pymavlink 2.4.49, common dialect.
// Fixed fixtures let CTest run without Python or pymavlink.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>
namespace mavlink_golden {
struct Packet { std::uint32_t id; bool v2; bool zero; bool signed_frame; std::string_view hex; };
inline constexpr std::array<Packet, 35> packets{{
    {0, false, false, false, "fe09172a110004000000020380040395ac"}, // heartbeat
    {0, false, true, false, "fe09172a1100000000000000000000f46d"}, // heartbeat
    {30, false, false, false, "fe1c172a111ee80300000000803e000000bf0000c03f000000000000000000000000e8da"}, // attitude
    {30, false, true, false, "fe1c172a111e000000000000000000000000000000000000000000000000000000000eb6"}, // attitude
    {33, false, false, false, "fe1c172a1121e803000000000000000000000000000004a60000000000000000000011f0"}, // global_position_int
    {33, false, true, false, "fe1c172a1121000000000000000000000000000000000000000000000000000000009bc0"}, // global_position_int
    {100, false, false, false, "fe1a172a1164e8030000000000000000003f000080be0000403f0c00f3ff07dcf0bc"}, // optical_flow
    {100, false, true, false, "fe1a172a11640000000000000000000000000000000000000000000000000000e548"}, // optical_flow
    {106, false, false, false, "fe2c172a116ae803000000000000102700000000003e000080be000000000000000000000000204e00000000a03f88ff09dbb1f4"}, // optical_flow_rad
    {106, false, true, false, "fe2c172a116a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c56d"}, // optical_flow_rad
    {132, false, false, false, "fe0e172a1184e803000014009001490000031900437e"}, // distance_sensor
    {132, false, true, false, "fe0e172a11840000000000000000000000000000846a"}, // distance_sensor
    {141, false, false, false, "fe20172a118de8030000000000000000ca420000cc420000803f0000504000000000000000008bcd"}, // altitude
    {141, false, true, false, "fe20172a118d0000000000000000000000000000000000000000000000000000000000000000c2d1"}, // altitude
    {0, true, false, false, "fd090000172a11000000040000000203800403714b"}, // heartbeat
    {0, true, true, false, "fd010000172a110000000012bc"}, // heartbeat
    {30, true, false, false, "fd100000172a111e0000e80300000000803e000000bf0000c03fe34e"}, // attitude
    {30, true, true, false, "fd010000172a111e000000c62e"}, // attitude
    {33, true, false, false, "fd120000172a11210000e803000000000000000000000000000004a655b0"}, // global_position_int
    {33, true, true, false, "fd010000172a1121000000182a"}, // global_position_int
    {100, true, false, false, "fd1a0000172a11640000e8030000000000000000003f000080be0000403f0c00f3ff07dc8c82"}, // optical_flow
    {100, true, true, false, "fd010000172a1164000000dd7f"}, // optical_flow
    {106, true, false, false, "fd2c0000172a116a0000e803000000000000102700000000003e000080be000000000000000000000000204e00000000a03f88ff09db55ba"}, // optical_flow_rad
    {106, true, true, false, "fd010000172a116a000000ca68"}, // optical_flow_rad
    {132, true, false, false, "fd0d0000172a11840000e8030000140090014900000319202d"}, // distance_sensor
    {132, true, true, false, "fd010000172a1184000000ee0c"}, // distance_sensor
    {141, true, false, false, "fd180000172a118d0000e8030000000000000000ca420000cc420000803f00005040375e"}, // altitude
    {141, true, true, false, "fd010000172a118d0000005781"}, // altitude
    {0, true, false, true, "fd090100172a1100000004000000020380040396b30587d6120000002a81dcad29f6"}, // signed heartbeat
    {30, true, false, true, "fd100100172a111e0000e80300000000803e000000bf0000c03f984a0587d612000000438d243ff069"}, // signed attitude
    {33, true, false, true, "fd120100172a11210000e803000000000000000000000000000004a61de20587d612000000c877764e9e66"}, // signed global_position_int
    {100, true, false, true, "fd1a0100172a11640000e8030000000000000000003f000080be0000403f0c00f3ff07dcb58f0587d612000000dd7d35bf5d02"}, // signed optical_flow
    {106, true, false, true, "fd2c0100172a116a0000e803000000000000102700000000003e000080be000000000000000000000000204e00000000a03f88ff09db367e0587d6120000001b7ec1759ac2"}, // signed optical_flow_rad
    {132, true, false, true, "fd0d0100172a11840000e80300001400900149000003197d840587d61200000033a355138d54"}, // signed distance_sensor
    {141, true, false, true, "fd180100172a118d0000e8030000000000000000ca420000cc420000803f00005040541e0587d612000000f102f3ce9fe0"}, // signed altitude
}};
} // namespace mavlink_golden
